### ISSUE TITLE
v1.0 roadmap

### ISSUE THREAD

**Issue by eddeee888** [eddeee888/graphql-code-generator-plugins#300]
- [ ] Support `schema-ast` OOTB
- [ ] Rename `fixObjectTypeResolvers` -> `fixResolvers`. Supported more than just object type since [v0.10](https://github.com/eddeee888/graphql-code-generator-plugins/pull/299)
- [ ] Rename package `@eddeee888/gcg-typescript-resolver-files` -> `???-server-preset`
- [ ] Remove warning about `presetConfig.typesPluginsConfig.namingConvention is not fully supported ...`. Supported since [v0.10](https://github.com/eddeee888/graphql-code-generator-plugins/pull/299)
